on:
  push:
    tags:
      - 'v*'

name: Create Release

jobs:
  build:
    # virtual machine
    runs-on: ubuntu-latest
    # Docker container
    container: "maven:3.6.3-jdk-8"
    steps:
    # Checkout the repository at tag v* (github ref)
    - name: Checkout repository
      uses: actions/checkout@v2
    - name: Build AxsUtilities
      run: |
        # build AxsUtilities.jar
        cd AxsUtilities
        mvn package
        mkdir -p /export
        mv target/AxsUtilities*.jar /export/AxsUtilities.jar
    - name: Package AXS
      # https://github.com/astronomy-commons/axs-spark/releases/download/axs-v3.0.0-preview2/axs-spark.tgz
      # Directory in tarball is spark-3.0.0-preview-bin-axs-spark/
      env:
        AXS_TAG: ${{ github.event.release.tag_name }}
      run: |
        AXS_SPARK_TAG=$(cat .axs_spark_tag)
        SPARK_DIR=$(echo $AXS_SPARK_TAG | sed 's/axs/bin-axs/')
        echo AXS_SPARK_TAG $AXS_SPARK_TAG SPARK_DIR $SPARK_DIR
        echo AXS_TAG $AXS_TAG
        curl -OL https://github.com/astronomy-commons/axs-spark/releases/download/$AXS_SPARK_TAG/axs-spark.tgz
        tar -xzf axs-spark.tgz
        cp /export/AxsUtilities.jar $SPARK_DIR/jars/
        cp -r axs/ $SPARK_DIR/python/
        mv $SPARK_DIR $AXS_TAG
        tar -czf $AXS_TAG.tgz $AXS_TAG
        mv $AXS_TAG.tgz /export/
    # Create the Github Release
    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
      with:
        tag_name: ${{ github.ref }}
        release_name: Release ${{ github.ref }}
        body: "AXS release ${{ github.ref }}"
        draft: true
        prerelease: false
    # Add jar to release
    - name: Upload Release Asset
      id: upload-release-asset 
      uses: actions/upload-release-asset@v1.0.1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }} # This pulls from the CREATE RELEASE step above, referencing it's ID to get its outputs object, which include a `upload_url`. See this blog post for more info: https://jasonet.co/posts/new-features-of-github-actions/#passing-data-to-future-steps 
        asset_path: /export/$AXS_TAG.jar
        asset_name: $AXS_TAG.tgz
        asset_content_type: application/zip-archive
